---
title: Палітри кольорів для стартових проєктів
hero_image: images/banner.png
description: Палітри кольорів для стартових проєктів.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Палітри кольорів для стартових проєктів
