title: Starter project colour palettes
hero_image: images/banner.png
description: Starter project colour palettes.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Starter project colour palettes
