---
title: Paletas de colores para proyectos iniciales
hero_image: images/banner.png
description: Paletas de colores para proyectos iniciales.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Paletas de colores para proyectos iniciales
